from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 500)
        Form.setStyleSheet("font: 12pt \"Franklin Gothic Medium\";\n"
"background-color: #f9f3d9")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.Menu_2 = QtWidgets.QWidget(Form)
        self.Menu_2.setFixedHeight(50)
        self.Menu_2.setStyleSheet("background-color: #5d4037 ")
        self.Menu_2.setObjectName("Menu_2")
        self.Menu = QtWidgets.QHBoxLayout(self.Menu_2)
        self.Menu.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Menu.setContentsMargins(-1, -1, -1, -1)
        self.Menu.setSpacing(6)
        self.Menu.setObjectName("Menu")
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.Menu_2)
        self.label.setStyleSheet("color: rgb(239, 231, 228);\n"
"font: 14pt \"Franklin Gothic Medium\"")
        self.label.setObjectName("label")
        self.Menu.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem1)
        self.Main = QtWidgets.QPushButton(self.Menu_2)
        self.Main.setStyleSheet("background-color:rgb(239, 231, 228)")
        self.Main.setObjectName("Main")
        self.Menu.addWidget(self.Main, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem2)
        self.Instruction = QtWidgets.QPushButton(self.Menu_2)
        self.Instruction.setStyleSheet("background-color:rgb(239, 231, 228)")
        self.Instruction.setObjectName("Instruction")
        self.Menu.addWidget(self.Instruction, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem3)
        self.TopRec = QtWidgets.QPushButton(self.Menu_2)
        self.TopRec.setStyleSheet("background-color:rgb(239, 231, 228)")
        self.TopRec.setObjectName("TopRec")
        self.Menu.addWidget(self.TopRec, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem4)
        self.Callories = QtWidgets.QPushButton(self.Menu_2)
        self.Callories.setStyleSheet("background-color:rgb(239, 231, 228)")
        self.Callories.setObjectName("Callories")
        self.Menu.addWidget(self.Callories, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.Menu_2, 0, 0)
        self.FindRec = QtWidgets.QWidget(Form)
        self.FindRec.setObjectName("FindRec")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.FindRec)
        self.hboxlayout.setObjectName("hboxlayout")
        self.verticalWidget = QtWidgets.QWidget(self.FindRec)
        self.verticalWidget.setStyleSheet("background-color: #FFFFF0")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalWidget.setMaximumHeight(100)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.CheckedIng = QtWidgets.QListWidget(self.verticalWidget)
        self.CheckedIng.setStyleSheet("Background-color:#FFFFF0")
        self.CheckedIng.setObjectName("CheckedIng")
        self.verticalLayout.addWidget(self.CheckedIng)
        self.hboxlayout.addWidget(self.verticalWidget)
        self.pushButton = QtWidgets.QPushButton(self.FindRec)
        self.pushButton.setStyleSheet("background-color:#FFFFF0")
        self.pushButton.setObjectName("pushButton")
        self.hboxlayout.addWidget(self.pushButton)
        self.FindRec.setMaximumHeight(100)
        self.gridLayout.addWidget(self.FindRec, 2, 0)
        self.Ingridients = QtWidgets.QWidget(Form)
        self.Ingridients.setMaximumHeight(600)
        self.Ingridients.setStyleSheet("background-color: #FFFFF0")
        self.Ingridients.setObjectName("Ingridients")
        self.Ingredients = QtWidgets.QVBoxLayout(self.Ingridients)
        self.Ingredients.setObjectName("Ingredients")
        self.Meat_title = QtWidgets.QLabel(self.Ingridients)
        self.Meat_title.setObjectName("Meat_title")
        self.Ingredients.addWidget(self.Meat_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Meat = QtWidgets.QWidget(self.Ingridients)
        self.Meat.setStyleSheet("background-color: #f9f3d9")
        self.Meat.setObjectName("Meat")
        self.Meat_CheckBox = QtWidgets.QHBoxLayout(self.Meat)
        self.Meat_CheckBox.setObjectName("Meat_CheckBox")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Meat_CheckBox.addItem(spacerItem5)
        self.checkBox = QtWidgets.QCheckBox(self.Meat)
        self.checkBox.setObjectName("checkBox")
        self.Meat_CheckBox.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.Meat)
        self.checkBox_2.setObjectName("checkBox_2")
        self.Meat_CheckBox.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.Meat)
        self.checkBox_3.setObjectName("checkBox_3")
        self.Meat_CheckBox.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.Meat)
        self.checkBox_4.setObjectName("checkBox_4")
        self.Meat_CheckBox.addWidget(self.checkBox_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Meat_CheckBox.addItem(spacerItem6)
        self.Ingredients.addWidget(self.Meat)
        self.Vegetables_2 = QtWidgets.QLabel(self.Ingridients)
        self.Vegetables_2.setObjectName("Vegetables_2")
        self.Ingredients.addWidget(self.Vegetables_2, 0, QtCore.Qt.AlignHCenter)
        self.Vegetables = QtWidgets.QWidget(self.Ingridients)
        self.Vegetables.setStyleSheet("background-color: #f9f3d9")
        self.Vegetables.setObjectName("Vegetables")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Vegetables)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.checkBox_5 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout.addWidget(self.checkBox_8)
        self.checkBox_13 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout.addWidget(self.checkBox_14)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.Ingredients.addWidget(self.Vegetables)
        self.Seafood = QtWidgets.QLabel(self.Ingridients)
        self.Seafood.setObjectName("Seafood")
        self.Ingredients.addWidget(self.Seafood, 0, QtCore.Qt.AlignHCenter)
        self.SeaFood = QtWidgets.QWidget(self.Ingridients)
        self.SeaFood.setStyleSheet("background-color: #f9f3d9")
        self.SeaFood.setObjectName("SeaFood")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SeaFood)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.checkBox_9 = QtWidgets.QCheckBox(self.SeaFood)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.SeaFood)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.SeaFood)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.SeaFood)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_2.addWidget(self.checkBox_12)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.Ingredients.addWidget(self.SeaFood)
        self.Pasta_title = QtWidgets.QLabel(self.Ingridients)
        self.Pasta_title.setObjectName("Pasta_title")
        self.Ingredients.addWidget(self.Pasta_title, 0, QtCore.Qt.AlignHCenter)
        self.Pasta = QtWidgets.QWidget(self.Ingridients)
        self.Pasta.setStyleSheet("background-color: #f9f3d9")
        self.Pasta.setObjectName("Pasta")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Pasta)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.checkBox_15 = QtWidgets.QCheckBox(self.Pasta)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.Pasta)
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout_3.addWidget(self.checkBox_16)
        self.checkBox_17 = QtWidgets.QCheckBox(self.Pasta)
        self.checkBox_17.setObjectName("checkBox_17")
        self.horizontalLayout_3.addWidget(self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.Pasta)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_3.addWidget(self.checkBox_18)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.Ingredients.addWidget(self.Pasta)
        self.Mushrooms_title = QtWidgets.QLabel(self.Ingridients)
        self.Mushrooms_title.setObjectName("Mushrooms_title")
        self.Ingredients.addWidget(self.Mushrooms_title, 0, QtCore.Qt.AlignHCenter)
        self.Mushrooms = QtWidgets.QWidget(self.Ingridients)
        self.Mushrooms.setStyleSheet("background-color: #f9f3d9")
        self.Mushrooms.setObjectName("Mushrooms")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Mushrooms)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.checkBox_21 = QtWidgets.QCheckBox(self.Mushrooms)
        self.checkBox_21.setObjectName("checkBox_21")
        self.horizontalLayout_4.addWidget(self.checkBox_21)
        self.checkBox_20 = QtWidgets.QCheckBox(self.Mushrooms)
        self.checkBox_20.setObjectName("checkBox_20")
        self.horizontalLayout_4.addWidget(self.checkBox_20)
        self.checkBox_22 = QtWidgets.QCheckBox(self.Mushrooms)
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_4.addWidget(self.checkBox_22)
        self.checkBox_19 = QtWidgets.QCheckBox(self.Mushrooms)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout_4.addWidget(self.checkBox_19)
        spacerItem14 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.Ingredients.addWidget(self.Mushrooms)
        self.Fruits_title = QtWidgets.QLabel(self.Ingridients)
        self.Fruits_title.setObjectName("Fruits_title")
        self.Ingredients.addWidget(self.Fruits_title, 0, QtCore.Qt.AlignHCenter)
        self.Fruits = QtWidgets.QWidget(self.Ingridients)
        self.Fruits.setStyleSheet("background-color: #f9f3d9")
        self.Fruits.setObjectName("Fruits")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Fruits)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.checkBox_24 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_6.addWidget(self.checkBox_24)
        self.checkBox_23 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_23.setObjectName("checkBox_23")
        self.horizontalLayout_6.addWidget(self.checkBox_23)
        self.checkBox_25 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_25.setObjectName("checkBox_25")
        self.horizontalLayout_6.addWidget(self.checkBox_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_26.setObjectName("checkBox_26")
        self.horizontalLayout_6.addWidget(self.checkBox_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_27.setObjectName("checkBox_27")
        self.horizontalLayout_6.addWidget(self.checkBox_27)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.Ingredients.addWidget(self.Fruits)
        self.Other_title = QtWidgets.QLabel(self.Ingridients)
        self.Other_title.setObjectName("Other_title")
        self.Ingredients.addWidget(self.Other_title, 0, QtCore.Qt.AlignHCenter)
        self.Other = QtWidgets.QWidget(self.Ingridients)
        self.Other.setStyleSheet("background-color: #f9f3d9")
        self.Other.setObjectName("Other")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Other)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem17 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.checkBox_31 = QtWidgets.QCheckBox(self.Other)
        self.checkBox_31.setObjectName("checkBox_31")
        self.horizontalLayout_7.addWidget(self.checkBox_31)
        self.checkBox_30 = QtWidgets.QCheckBox(self.Other)
        self.checkBox_30.setObjectName("checkBox_30")
        self.horizontalLayout_7.addWidget(self.checkBox_30)
        self.checkBox_29 = QtWidgets.QCheckBox(self.Other)
        self.checkBox_29.setObjectName("checkBox_29")
        self.horizontalLayout_7.addWidget(self.checkBox_29)
        self.checkBox_28 = QtWidgets.QCheckBox(self.Other)
        self.checkBox_28.setObjectName("checkBox_28")
        self.horizontalLayout_7.addWidget(self.checkBox_28)
        spacerItem18 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.Ingredients.addWidget(self.Other)
        self.gridLayout.addWidget(self.Ingridients, 1, 0)
        self.Instructions = QtWidgets.QListWidget(Form)
        self.Instructions.setStyleSheet("background-color: #FFFFF0")
        self.Instructions.setObjectName("Instructions")
        self.gridLayout.addWidget(self.Instructions, 1, 0)
        self.TopRec_3 = QtWidgets.QWidget(Form)
        self.TopRec_3.setObjectName("TopRec_3")
        self.TopRec_2 = QtWidgets.QVBoxLayout(self.TopRec_3)
        self.TopRec_2.setObjectName("TopRec_2")
        self.TopRec2 = QtWidgets.QWidget(self.TopRec_3)
        self.TopRec2.setObjectName("TopRec2")
        self.TopRec2.setFixedHeight(180)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.TopRec2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")

        self.pixmap1 = QPixmap()
        self.labelBack1 = QtWidgets.QLabel(self.TopRec_3)
        self.labelBack1.setPixmap(self.pixmap1)
        self.labelBack1.setObjectName("labelBack1")
        self.horizontalLayout_10.addWidget(self.labelBack1)

        self.listWidget_1 = QtWidgets.QListWidget(self.TopRec2)
        self.listWidget_1.setStyleSheet("background-color:#FFFFF0")
        self.listWidget_1.setObjectName("listWidget_1")
        self.horizontalLayout_10.addWidget(self.listWidget_1)

        self.pushButton_3 = QtWidgets.QPushButton(self.TopRec2)
        self.pushButton_3.setStyleSheet("background-color:#FFFFF0")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)

        self.TopRec_2.addWidget(self.TopRec2)
        self.TopRec3 = QtWidgets.QWidget(self.TopRec_3)
        self.TopRec3.setObjectName("TopRec3")
        self.TopRec3.setFixedHeight(180)

        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.TopRec3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")

        self.pixmap2 = QPixmap()
        self.pixmap2 = self.pixmap1.scaled(180, 180)
        self.labelBack2 = QtWidgets.QLabel(self.TopRec_3)
        self.labelBack2.setObjectName("labelBack2")
        self.labelBack2.setPixmap(self.pixmap2)
        self.horizontalLayout_11.addWidget(self.labelBack2)

        self.listWidget_2 = QtWidgets.QListWidget(self.TopRec3)
        self.listWidget_2.setStyleSheet("background-color:#FFFFF0")
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout_11.addWidget(self.listWidget_2)

        self.pushButton_4 = QtWidgets.QPushButton(self.TopRec3)
        self.pushButton_4.setStyleSheet("background-color:#FFFFF0")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_11.addWidget(self.pushButton_4)

        self.TopRec_2.addWidget(self.TopRec3)
        self.TopRec1 = QtWidgets.QWidget(self.TopRec_3)
        self.TopRec1.setObjectName("TopRec1")
        self.TopRec1.setFixedHeight(180)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TopRec1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")

        self.pixmap3 = QPixmap()
        self.pixmap3 = self.pixmap1.scaled(180, 180)
        self.labelBack3 = QtWidgets.QLabel(self.TopRec_3)
        self.labelBack3.setObjectName("labelBack3")
        self.labelBack3.setPixmap(self.pixmap3)
        self.horizontalLayout_9.addWidget(self.labelBack3)

        self.listWidget_3 = QtWidgets.QListWidget(self.TopRec1)
        self.listWidget_3.setStyleSheet("background-color:#FFFFF0")
        self.listWidget_3.setObjectName("listWidget_3")

        self.horizontalLayout_9.addWidget(self.listWidget_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.TopRec1)
        self.pushButton_2.setStyleSheet("background-color:#FFFFF0")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.TopRec_2.addWidget(self.TopRec1)
        self.gridLayout.addWidget(self.TopRec_3, 1, 0)
        self.label_error = QtWidgets.QLabel(self.TopRec_3)
        self.label_error.setObjectName("label_error")
        self.TopRec_2.addWidget(self.label_error, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.Callories_3 = QtWidgets.QWidget(Form)
        self.Callories_3.setObjectName("Callories_3")
        self.Callories_2 = QtWidgets.QVBoxLayout(self.Callories_3)
        self.Callories_2.setObjectName("Callories_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.Callories_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.Callories_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem19 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.Callories_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Title = QtWidgets.QLineEdit(self.Callories_3)
        self.Title.setStyleSheet("background-color:#FFFFF0")
        self.Title.setObjectName("Title")
        self.horizontalLayout_12.addWidget(self.Title)
        self.Weight = QtWidgets.QLineEdit(self.Callories_3)
        self.Weight.setStyleSheet("background-color:#FFFFF0")
        self.Weight.setObjectName("Weight")
        self.horizontalLayout_12.addWidget(self.Weight)
        self.pushButton_5 = QtWidgets.QPushButton(self.Callories_3)
        self.pushButton_5.setStyleSheet("background-color:#FFFFF0")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_12.addWidget(self.pushButton_5)
        self.Callories_2.addLayout(self.horizontalLayout_12)
        self.label_callories = QtWidgets.QLabel(self.Callories_3)
        self.label_callories.setObjectName("label_callories")
        self.Callories_2.addWidget(self.label_callories, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.Callories_3, 1, 0)

        spacerItem20 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem20, 2, 0)

        self.checkBox.stateChanged.connect(self.change_state)
        self.checkBox_2.stateChanged.connect(self.change_state)
        self.checkBox_3.stateChanged.connect(self.change_state)
        self.checkBox_4.stateChanged.connect(self.change_state)
        self.checkBox_5.stateChanged.connect(self.change_state)
        self.checkBox_6.stateChanged.connect(self.change_state)
        self.checkBox_7.stateChanged.connect(self.change_state)
        self.checkBox_8.stateChanged.connect(self.change_state)
        self.checkBox_9.stateChanged.connect(self.change_state)
        self.checkBox_10.stateChanged.connect(self.change_state)
        self.checkBox_11.stateChanged.connect(self.change_state)
        self.checkBox_12.stateChanged.connect(self.change_state)
        self.checkBox_13.stateChanged.connect(self.change_state)
        self.checkBox_14.stateChanged.connect(self.change_state)
        self.checkBox_15.stateChanged.connect(self.change_state)
        self.checkBox_16.stateChanged.connect(self.change_state)
        self.checkBox_17.stateChanged.connect(self.change_state)
        self.checkBox_18.stateChanged.connect(self.change_state)
        self.checkBox_19.stateChanged.connect(self.change_state)
        self.checkBox_2.stateChanged.connect(self.change_state)
        self.checkBox_20.stateChanged.connect(self.change_state)
        self.checkBox_21.stateChanged.connect(self.change_state)
        self.checkBox_22.stateChanged.connect(self.change_state)
        self.checkBox_23.stateChanged.connect(self.change_state)
        self.checkBox_24.stateChanged.connect(self.change_state)
        self.checkBox_25.stateChanged.connect(self.change_state)
        self.checkBox_26.stateChanged.connect(self.change_state)
        self.checkBox_27.stateChanged.connect(self.change_state)
        self.checkBox_28.stateChanged.connect(self.change_state)
        self.checkBox_29.stateChanged.connect(self.change_state)
        self.checkBox_30.stateChanged.connect(self.change_state)
        self.checkBox_31.stateChanged.connect(self.change_state)

        self.text2 = " 1.Чтобы найти рецепты, выберите продукты которые у вас есть. Затем нажмите кнопку Найти рецепты, будут показаны все доступные рецепты.\n\n" \
               " 2.В любой рецепт можно нажать, там будет показана подробная информация как приговить данное блюдо.\n\n" \
               " 3.В вкладкеТоп рецепты, собраны лучшие рецепты нашего приложения которые получили большинство оценок среди пользователей.\n\n" \
               " 4.Если вы следите за своей фигурой, то можете перейти в раздел для подсчета калорий. Там можно получить информацию о каждом ингредиенте.\n\n" \
               " 5.Приятного аппетита дорогие пользователи"
        self.item = QtWidgets.QListWidgetItem(self.text2)
        self.Instructions.addItem(self.item)

        self.arr = []
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def change_state(self):
        self.CheckedIng.clear()
        self.arr.clear()
        self.text = ""
        if self.checkBox.isChecked(): self.arr.append("Курица. ")
        if self.checkBox_2.isChecked(): self.arr.append("Свинина. ")
        if self.checkBox_3.isChecked(): self.arr.append("Говядина. ")
        if self.checkBox_4.isChecked(): self.arr.append("Баранина. ")
        if self.checkBox_5.isChecked(): self.arr.append("Картофель. ")
        if self.checkBox_6.isChecked(): self.arr.append("Капуста. ")
        if self.checkBox_7.isChecked(): self.arr.append("Помидор. ")
        if self.checkBox_8.isChecked(): self.arr.append("Огурец. ")
        if self.checkBox_9.isChecked(): self.arr.append("Семга. ")
        if self.checkBox_10.isChecked(): self.arr.append("Мидии. ")
        if self.checkBox_11.isChecked(): self.arr.append("Тунец. ")
        if self.checkBox_12.isChecked(): self.arr.append("Креветки. ")
        if self.checkBox_13.isChecked(): self.arr.append("Морковь. ")
        if self.checkBox_14.isChecked(): self.arr.append("Лук. ")
        if self.checkBox_15.isChecked(): self.arr.append("Вермишель. ")
        if self.checkBox_16.isChecked(): self.arr.append("Спагетти. ")
        if self.checkBox_17.isChecked(): self.arr.append("Рожки. ")
        if self.checkBox_18.isChecked(): self.arr.append("Фунчоза. ")
        if self.checkBox_19.isChecked(): self.arr.append("Лисички. ")
        if self.checkBox_20.isChecked(): self.arr.append("Белые грибы. ")
        if self.checkBox_21.isChecked(): self.arr.append("Шампиньоны. ")
        if self.checkBox_22.isChecked(): self.arr.append("Опята. ")
        if self.checkBox_23.isChecked(): self.arr.append("Яблоко. ")
        if self.checkBox_24.isChecked(): self.arr.append("Банан. ")
        if self.checkBox_25.isChecked(): self.arr.append("Апельсин. ")
        if self.checkBox_26.isChecked(): self.arr.append("Дыня. ")
        if self.checkBox_27.isChecked(): self.arr.append("Киви. ")
        if self.checkBox_28.isChecked(): self.arr.append("Укроп. ")
        if self.checkBox_29.isChecked(): self.arr.append("Маргарин. ")
        if self.checkBox_30.isChecked(): self.arr.append("Сыр. ")
        if self.checkBox_31.isChecked(): self.arr.append("Яйцо. ")

        for i in self.arr:
            self.text += i

        self.item = QtWidgets.QListWidgetItem(self.text)
        self.CheckedIng.addItem(self.item)

    def updateimg1(self, img1):
        self.pixmap1 = QPixmap("Рецепты/" + img1 + ".jpg")
        self.pixmap1 = self.pixmap1.scaled(220, 180)
        self.labelBack1.setPixmap(self.pixmap1)

    def updateimg2(self, img2):
        self.pixmap2 = QPixmap("Рецепты/" + img2 + ".jpg")
        self.pixmap2 = self.pixmap2.scaled(220, 180)
        self.labelBack2.setPixmap(self.pixmap2)

    def updateimg3(self, img3):
        self.pixmap3 = QPixmap("Рецепты/" + img3 + ".jpg")
        self.pixmap3 = self.pixmap3.scaled(220, 180)
        self.labelBack3.setPixmap(self.pixmap3)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Домашний повар"))
        self.label.setText(_translate("Form", "Домашний повар"))
        self.Main.setText(_translate("Form", "Главная"))
        self.Instruction.setText(_translate("Form", "Инструкция"))
        self.TopRec.setText(_translate("Form", "Топ рецепты"))
        self.Callories.setText(_translate("Form", "Калории"))
        self.label_2.setText(_translate("Form", "Выбранные ингредиенты:"))
        self.pushButton.setText(_translate("Form", "Найти рецепты"))
        self.Meat_title.setText(_translate("Form", "Мясо"))
        self.checkBox.setText(_translate("Form", "Курица"))
        self.checkBox_2.setText(_translate("Form", "Свинина"))
        self.checkBox_3.setText(_translate("Form", "Говядина"))
        self.checkBox_4.setText(_translate("Form", "Баранина"))
        self.Vegetables_2.setText(_translate("Form", "Овощи"))
        self.checkBox_5.setText(_translate("Form", "Картофель"))
        self.checkBox_6.setText(_translate("Form", "Капуста"))
        self.checkBox_7.setText(_translate("Form", "Помидор"))
        self.checkBox_8.setText(_translate("Form", "Огурец"))
        self.checkBox_13.setText(_translate("Form", "Морковь"))
        self.checkBox_14.setText(_translate("Form", "Лук"))
        self.Seafood.setText(_translate("Form", "Морепродукты"))
        self.checkBox_9.setText(_translate("Form", "Семга"))
        self.checkBox_10.setText(_translate("Form", "Мидии"))
        self.checkBox_11.setText(_translate("Form", "Тунец"))
        self.checkBox_12.setText(_translate("Form", "Креветки"))
        self.Pasta_title.setText(_translate("Form", "Макароны"))
        self.checkBox_15.setText(_translate("Form", "Вермишель"))
        self.checkBox_16.setText(_translate("Form", "Спагетти"))
        self.checkBox_17.setText(_translate("Form", "Рожки"))
        self.checkBox_18.setText(_translate("Form", "Фунчоза"))
        self.Mushrooms_title.setText(_translate("Form", "Грибы"))
        self.checkBox_21.setText(_translate("Form", "Шампиньоны"))
        self.checkBox_20.setText(_translate("Form", "Белые грибы"))
        self.checkBox_22.setText(_translate("Form", "Опята"))
        self.checkBox_19.setText(_translate("Form", "Лисички"))
        self.Fruits_title.setText(_translate("Form", "Фрукты"))
        self.checkBox_24.setText(_translate("Form", "Банан"))
        self.checkBox_23.setText(_translate("Form", "Яблоко"))
        self.checkBox_25.setText(_translate("Form", "Апельсин"))
        self.checkBox_26.setText(_translate("Form", "Дыня"))
        self.checkBox_27.setText(_translate("Form", "Киви"))
        self.Other_title.setText(_translate("Form", "Разное"))
        self.checkBox_31.setText(_translate("Form", "Яйцо"))
        self.checkBox_30.setText(_translate("Form", "Сыр"))
        self.checkBox_29.setText(_translate("Form", "Маргарин"))
        self.checkBox_28.setText(_translate("Form", "Укроп"))
        self.pushButton_3.setText(_translate("Form", "Посмотреть рецепт"))
        self.pushButton_4.setText(_translate("Form", "Посмотреть рецепт"))
        self.pushButton_2.setText(_translate("Form", "Посмотреть рецепт"))
        self.label_3.setText(_translate("Form", "Название продукта"))
        self.label_4.setText(_translate("Form", "Масса(гр.)"))
        self.pushButton_5.setText(_translate("Form", "Рассчитать"))
        self.label_callories.setText(_translate("Form", ""))
        self.label_error.setText(_translate("Form", ""))


class WindowRecipe(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 600)
        Form.setStyleSheet("font: 12pt \"Franklin Gothic Medium\";\n"
                           "background-color: #f9f3d9")
        self.grid = QtWidgets.QGridLayout(Form)
        self.grid.setObjectName("grid")

        self.label = QtWidgets.QLabel()
        self.label.setObjectName("label")
        self.grid.addWidget(self.label, 0, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.pixmap1 = QPixmap()
        self.labelBack1 = QtWidgets.QLabel()
        self.labelBack1.setPixmap(self.pixmap1)
        self.labelBack1.setObjectName("labelBack1")
        self.grid.addWidget(self.labelBack1, 1, 0)

        self.pixmap2 = QPixmap()
        self.labelBack2 = QtWidgets.QLabel()
        self.labelBack2.setPixmap(self.pixmap2)
        self.labelBack2.setObjectName("labelBack2")
        self.grid.addWidget(self.labelBack2, 2, 0)

        self.pixmap3 = QPixmap()
        self.labelBack3 = QtWidgets.QLabel()
        self.labelBack3.setPixmap(self.pixmap3)
        self.labelBack3.setObjectName("labelBack3")
        self.grid.addWidget(self.labelBack3, 3, 0)

        self.pixmap4 = QPixmap()
        self.labelBack4 = QtWidgets.QLabel()
        self.labelBack4.setPixmap(self.pixmap4)
        self.labelBack4.setObjectName("labelBack4")
        self.grid.addWidget(self.labelBack4, 4, 0)

        self.pixmap5 = QPixmap()
        self.labelBack5 = QtWidgets.QLabel()
        self.labelBack5.setPixmap(self.pixmap5)
        self.labelBack5.setObjectName("labelBack5")
        self.grid.addWidget(self.labelBack5, 5, 0)

        self.Step1 = QtWidgets.QListWidget(Form)
        self.Step1.setWordWrap(True)
        self.Step1.setObjectName("Step1")
        self.Step1.setStyleSheet("background-color:#FFFFF0")
        self.grid.addWidget(self.Step1, 1, 1)

        self.Step2 = QtWidgets.QListWidget(Form)
        self.Step2.setWordWrap(True)
        self.Step2.setObjectName("Step2")
        self.Step2.setStyleSheet("background-color:#FFFFF0")
        self.grid.addWidget(self.Step2, 2, 1)

        self.Step3 = QtWidgets.QListWidget(Form)
        self.Step3.setWordWrap(True)
        self.Step3.setObjectName("Step3")
        self.Step3.setStyleSheet("background-color:#FFFFF0")
        self.grid.addWidget(self.Step3, 3, 1)

        self.Step4 = QtWidgets.QListWidget(Form)
        self.Step4.setWordWrap(True)
        self.Step4.setObjectName("Step4")
        self.Step4.setStyleSheet("background-color:#FFFFF0")
        self.grid.addWidget(self.Step4, 4, 1)

        self.Step5 = QtWidgets.QListWidget(Form)
        self.Step5.setWordWrap(True)
        self.Step5.setObjectName("Step5")
        self.Step5.setStyleSheet("background-color:#FFFFF0")
        self.grid.addWidget(self.Step5, 5, 1)

        self.Like = QtWidgets.QPushButton(Form)
        self.Like.setObjectName("Like")
        self.Like.setStyleSheet("background-color:#FFFFF0")
        self.grid.addWidget(self.Like, 6, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def update_imgs(self, num):
        self.pixmap1 = QPixmap("Рецепты/" + str(num) + "1.jpg")
        self.pixmap1 = self.pixmap1.scaled(170, 130)
        self.labelBack1.setPixmap(self.pixmap1)

        self.pixmap2 = QPixmap("Рецепты/" + str(num) + "2.jpg")
        self.pixmap2 = self.pixmap2.scaled(170, 130)
        self.labelBack2.setPixmap(self.pixmap2)

        self.pixmap3 = QPixmap("Рецепты/" + str(num) + "3.jpg")
        self.pixmap3 = self.pixmap3.scaled(170, 130)
        self.labelBack3.setPixmap(self.pixmap3)

        self.pixmap4 = QPixmap("Рецепты/" + str(num) + "4.jpg")
        self.pixmap4 = self.pixmap4.scaled(170, 130)
        self.labelBack4.setPixmap(self.pixmap4)

        self.pixmap5 = QPixmap("Рецепты/" + str(num) + "5.jpg")
        self.pixmap5 = self.pixmap5.scaled(170, 130)
        self.labelBack5.setPixmap(self.pixmap5)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Рецепт"))
        self.Like.setText(_translate("Form", "Нравится"))
        self.label.setText(_translate("Form", ""))
