from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 500)
        Form.setStyleSheet("font: 12pt \"Franklin Gothic Medium\";\n"
"background-color: #f9f3d9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Menu_2 = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu_2.sizePolicy().hasHeightForWidth())
        self.Menu_2.setSizePolicy(sizePolicy)
        self.Menu_2.setStyleSheet("background-color: #5d4037 ")
        self.Menu_2.setObjectName("Menu_2")
        self.Menu = QtWidgets.QHBoxLayout(self.Menu_2)
        self.Menu.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Menu.setContentsMargins(1, 1, -1, -1)
        self.Menu.setSpacing(6)
        self.Menu.setObjectName("Menu")
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.Menu_2)
        self.label.setStyleSheet("color: rgb(239, 231, 228);\n"
"font: 14pt \"Franklin Gothic Medium\"")
        self.label.setObjectName("label")
        self.Menu.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem1)
        self.Main = QtWidgets.QPushButton(self.Menu_2)
        self.Main.setStyleSheet("background-color:rgb(239, 231, 228)")
        self.Main.setObjectName("Main")
        self.Menu.addWidget(self.Main, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem2)
        self.Instruction = QtWidgets.QPushButton(self.Menu_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Instruction.sizePolicy().hasHeightForWidth())
        self.Instruction.setSizePolicy(sizePolicy)
        self.Instruction.setStyleSheet("background-color:rgb(239, 231, 228)")
        self.Instruction.setObjectName("Instruction")
        self.Menu.addWidget(self.Instruction, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem3)
        self.TopRec = QtWidgets.QPushButton(self.Menu_2)
        self.TopRec.setStyleSheet("background-color:rgb(239, 231, 228)")
        self.TopRec.setObjectName("TopRec")
        self.Menu.addWidget(self.TopRec, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Menu.addItem(spacerItem4)
        self.Callories = QtWidgets.QPushButton(self.Menu_2)
        self.Callories.setStyleSheet("background-color:rgb(239, 231, 228)")
        self.Callories.setObjectName("Callories")
        self.Menu.addWidget(self.Callories, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.Menu_2)
        self.FindRec = QtWidgets.QWidget(Form)
        self.FindRec.setObjectName("FindRec")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.FindRec)
        self.hboxlayout.setObjectName("hboxlayout")
        self.verticalWidget = QtWidgets.QWidget(self.FindRec)
        self.verticalWidget.setStyleSheet("background-color: #FFFFF0")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.CheckedIng = QtWidgets.QListView(self.verticalWidget)
        self.CheckedIng.setStyleSheet("Background-color:#FFFFF0")
        self.CheckedIng.setObjectName("CheckedIng")
        self.verticalLayout.addWidget(self.CheckedIng)
        self.hboxlayout.addWidget(self.verticalWidget)
        self.pushButton = QtWidgets.QPushButton(self.FindRec)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color:#FFFFF0")
        self.pushButton.setObjectName("pushButton")
        self.hboxlayout.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.FindRec)
        self.Ingridients = QtWidgets.QWidget(Form)
        self.Ingridients.setStyleSheet("background-color: #FFFFF0")
        self.Ingridients.setObjectName("Ingridients")
        self.Ingredients = QtWidgets.QVBoxLayout(self.Ingridients)
        self.Ingredients.setObjectName("Ingredients")
        self.Meat_title = QtWidgets.QLabel(self.Ingridients)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Meat_title.sizePolicy().hasHeightForWidth())
        self.Meat_title.setSizePolicy(sizePolicy)
        self.Meat_title.setMinimumSize(QtCore.QSize(0, 19))
        self.Meat_title.setMaximumSize(QtCore.QSize(16777215, 19))
        self.Meat_title.setStyleSheet("")
        self.Meat_title.setObjectName("Meat_title")
        self.Ingredients.addWidget(self.Meat_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Meat = QtWidgets.QWidget(self.Ingridients)
        self.Meat.setStyleSheet("background-color: #f9f3d9")
        self.Meat.setObjectName("Meat")
        self.Meat_CheckBox = QtWidgets.QHBoxLayout(self.Meat)
        self.Meat_CheckBox.setObjectName("Meat_CheckBox")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Meat_CheckBox.addItem(spacerItem5)
        self.checkBox = QtWidgets.QCheckBox(self.Meat)
        self.checkBox.setObjectName("checkBox")
        self.Meat_CheckBox.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.Meat)
        self.checkBox_2.setObjectName("checkBox_2")
        self.Meat_CheckBox.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.Meat)
        self.checkBox_3.setObjectName("checkBox_3")
        self.Meat_CheckBox.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.Meat)
        self.checkBox_4.setObjectName("checkBox_4")
        self.Meat_CheckBox.addWidget(self.checkBox_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Meat_CheckBox.addItem(spacerItem6)
        self.Ingredients.addWidget(self.Meat)
        self.Vegetables_2 = QtWidgets.QLabel(self.Ingridients)
        self.Vegetables_2.setObjectName("Vegetables_2")
        self.Ingredients.addWidget(self.Vegetables_2, 0, QtCore.Qt.AlignHCenter)
        self.Vegetables = QtWidgets.QWidget(self.Ingridients)
        self.Vegetables.setStyleSheet("background-color: #f9f3d9")
        self.Vegetables.setObjectName("Vegetables")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Vegetables)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.checkBox_5 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout.addWidget(self.checkBox_8)
        self.checkBox_13 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.Vegetables)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout.addWidget(self.checkBox_14)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.Ingredients.addWidget(self.Vegetables)
        self.Seafood = QtWidgets.QLabel(self.Ingridients)
        self.Seafood.setObjectName("Seafood")
        self.Ingredients.addWidget(self.Seafood, 0, QtCore.Qt.AlignHCenter)
        self.SeaFood = QtWidgets.QWidget(self.Ingridients)
        self.SeaFood.setStyleSheet("background-color: #f9f3d9")
        self.SeaFood.setObjectName("SeaFood")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SeaFood)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.checkBox_9 = QtWidgets.QCheckBox(self.SeaFood)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.SeaFood)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.SeaFood)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.SeaFood)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_2.addWidget(self.checkBox_12)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.Ingredients.addWidget(self.SeaFood)
        self.Pasta_title = QtWidgets.QLabel(self.Ingridients)
        self.Pasta_title.setObjectName("Pasta_title")
        self.Ingredients.addWidget(self.Pasta_title, 0, QtCore.Qt.AlignHCenter)
        self.Pasta = QtWidgets.QWidget(self.Ingridients)
        self.Pasta.setStyleSheet("background-color: #f9f3d9")
        self.Pasta.setObjectName("Pasta")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Pasta)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.checkBox_15 = QtWidgets.QCheckBox(self.Pasta)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.Pasta)
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout_3.addWidget(self.checkBox_16)
        self.checkBox_17 = QtWidgets.QCheckBox(self.Pasta)
        self.checkBox_17.setObjectName("checkBox_17")
        self.horizontalLayout_3.addWidget(self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.Pasta)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_3.addWidget(self.checkBox_18)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.Ingredients.addWidget(self.Pasta)
        self.Mushrooms_title = QtWidgets.QLabel(self.Ingridients)
        self.Mushrooms_title.setObjectName("Mushrooms_title")
        self.Ingredients.addWidget(self.Mushrooms_title, 0, QtCore.Qt.AlignHCenter)
        self.Mushrooms = QtWidgets.QWidget(self.Ingridients)
        self.Mushrooms.setStyleSheet("background-color: #f9f3d9")
        self.Mushrooms.setObjectName("Mushrooms")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Mushrooms)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.checkBox_21 = QtWidgets.QCheckBox(self.Mushrooms)
        self.checkBox_21.setObjectName("checkBox_21")
        self.horizontalLayout_4.addWidget(self.checkBox_21)
        self.checkBox_20 = QtWidgets.QCheckBox(self.Mushrooms)
        self.checkBox_20.setObjectName("checkBox_20")
        self.horizontalLayout_4.addWidget(self.checkBox_20)
        self.checkBox_22 = QtWidgets.QCheckBox(self.Mushrooms)
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_4.addWidget(self.checkBox_22)
        self.checkBox_19 = QtWidgets.QCheckBox(self.Mushrooms)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout_4.addWidget(self.checkBox_19)
        spacerItem14 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.Ingredients.addWidget(self.Mushrooms)
        self.Fruits_title = QtWidgets.QLabel(self.Ingridients)
        self.Fruits_title.setObjectName("Fruits_title")
        self.Ingredients.addWidget(self.Fruits_title, 0, QtCore.Qt.AlignHCenter)
        self.Fruits = QtWidgets.QWidget(self.Ingridients)
        self.Fruits.setStyleSheet("background-color: #f9f3d9")
        self.Fruits.setObjectName("Fruits")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Fruits)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.checkBox_24 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_6.addWidget(self.checkBox_24)
        self.checkBox_23 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_23.setObjectName("checkBox_23")
        self.horizontalLayout_6.addWidget(self.checkBox_23)
        self.checkBox_25 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_25.setObjectName("checkBox_25")
        self.horizontalLayout_6.addWidget(self.checkBox_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_26.setObjectName("checkBox_26")
        self.horizontalLayout_6.addWidget(self.checkBox_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.Fruits)
        self.checkBox_27.setObjectName("checkBox_27")
        self.horizontalLayout_6.addWidget(self.checkBox_27)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.Ingredients.addWidget(self.Fruits)
        self.Other_title = QtWidgets.QLabel(self.Ingridients)
        self.Other_title.setObjectName("Other_title")
        self.Ingredients.addWidget(self.Other_title, 0, QtCore.Qt.AlignHCenter)
        self.Other = QtWidgets.QWidget(self.Ingridients)
        self.Other.setStyleSheet("background-color: #f9f3d9")
        self.Other.setObjectName("Other")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Other)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem17 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.checkBox_31 = QtWidgets.QCheckBox(self.Other)
        self.checkBox_31.setObjectName("checkBox_31")
        self.horizontalLayout_7.addWidget(self.checkBox_31)
        self.checkBox_30 = QtWidgets.QCheckBox(self.Other)
        self.checkBox_30.setObjectName("checkBox_30")
        self.horizontalLayout_7.addWidget(self.checkBox_30)
        self.checkBox_29 = QtWidgets.QCheckBox(self.Other)
        self.checkBox_29.setObjectName("checkBox_29")
        self.horizontalLayout_7.addWidget(self.checkBox_29)
        self.checkBox_28 = QtWidgets.QCheckBox(self.Other)
        self.checkBox_28.setObjectName("checkBox_28")
        self.horizontalLayout_7.addWidget(self.checkBox_28)
        spacerItem18 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.Ingredients.addWidget(self.Other)
        self.verticalLayout_2.addWidget(self.Ingridients)
        self.Instructions = QtWidgets.QListView(Form)
        self.Instructions.setStyleSheet("background-color: #FFFFF0")
        self.Instructions.setObjectName("Instructions")
        self.verticalLayout_2.addWidget(self.Instructions)
        self.TopRec_3 = QtWidgets.QWidget(Form)
        self.TopRec_3.setObjectName("TopRec_3")
        self.TopRec_2 = QtWidgets.QVBoxLayout(self.TopRec_3)
        self.TopRec_2.setObjectName("TopRec_2")
        self.TopRec2 = QtWidgets.QWidget(self.TopRec_3)
        self.TopRec2.setObjectName("TopRec2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.TopRec2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_2 = QtWidgets.QWidget(self.TopRec2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_10.addWidget(self.widget_2)
        self.listView = QtWidgets.QListView(self.TopRec2)
        self.listView.setStyleSheet("background-color:#FFFFF0")
        self.listView.setObjectName("listView")
        self.horizontalLayout_10.addWidget(self.listView)
        self.pushButton_3 = QtWidgets.QPushButton(self.TopRec2)
        self.pushButton_3.setStyleSheet("background-color:#FFFFF0")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.TopRec_2.addWidget(self.TopRec2)
        self.TopRec3 = QtWidgets.QWidget(self.TopRec_3)
        self.TopRec3.setObjectName("TopRec3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.TopRec3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_3 = QtWidgets.QWidget(self.TopRec3)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_11.addWidget(self.widget_3)
        self.listView_2 = QtWidgets.QListView(self.TopRec3)
        self.listView_2.setStyleSheet("background-color:#FFFFF0")
        self.listView_2.setObjectName("listView_2")
        self.horizontalLayout_11.addWidget(self.listView_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.TopRec3)
        self.pushButton_4.setStyleSheet("background-color:#FFFFF0")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_11.addWidget(self.pushButton_4)
        self.TopRec_2.addWidget(self.TopRec3)
        self.TopRec1 = QtWidgets.QWidget(self.TopRec_3)
        self.TopRec1.setObjectName("TopRec1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TopRec1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget = QtWidgets.QWidget(self.TopRec1)
        self.widget.setObjectName("widget")
        self.horizontalLayout_9.addWidget(self.widget)
        self.listWidget = QtWidgets.QListWidget(self.TopRec1)
        self.listWidget.setStyleSheet("background-color:#FFFFF0")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_9.addWidget(self.listWidget)
        self.pushButton_2 = QtWidgets.QPushButton(self.TopRec1)
        self.pushButton_2.setStyleSheet("background-color:#FFFFF0")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.TopRec_2.addWidget(self.TopRec1)
        self.verticalLayout_2.addWidget(self.TopRec_3)
        self.Callories_3 = QtWidgets.QWidget(Form)
        self.Callories_3.setObjectName("Callories_3")
        self.Callories_2 = QtWidgets.QVBoxLayout(self.Callories_3)
        self.Callories_2.setObjectName("Callories_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.Callories_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.Callories_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem19 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.Callories_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Title = QtWidgets.QLineEdit(self.Callories_3)
        self.Title.setStyleSheet("background-color:#FFFFF0")
        self.Title.setObjectName("Title")
        self.horizontalLayout_12.addWidget(self.Title)
        self.Weight = QtWidgets.QLineEdit(self.Callories_3)
        self.Weight.setStyleSheet("background-color:#FFFFF0")
        self.Weight.setObjectName("Weight")
        self.horizontalLayout_12.addWidget(self.Weight)
        self.pushButton_5 = QtWidgets.QPushButton(self.Callories_3)
        self.pushButton_5.setStyleSheet("background-color:#FFFFF0")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_12.addWidget(self.pushButton_5)
        self.Callories_2.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addWidget(self.Callories_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Домашний повар"))
        self.Main.setText(_translate("Form", "Главная"))
        self.Instruction.setText(_translate("Form", "Инструкция"))
        self.TopRec.setText(_translate("Form", "Топ рецепты"))
        self.Callories.setText(_translate("Form", "Каллории"))
        self.label_2.setText(_translate("Form", "Выбранные ингридиенты:"))
        self.pushButton.setText(_translate("Form", "Найти рецепты"))
        self.Meat_title.setText(_translate("Form", "Мясо"))
        self.checkBox.setText(_translate("Form", "Курица"))
        self.checkBox_2.setText(_translate("Form", "Свинина"))
        self.checkBox_3.setText(_translate("Form", "Говядина"))
        self.checkBox_4.setText(_translate("Form", "Баранина"))
        self.Vegetables_2.setText(_translate("Form", "Овощи"))
        self.checkBox_5.setText(_translate("Form", "Картофель"))
        self.checkBox_6.setText(_translate("Form", "Капуста"))
        self.checkBox_7.setText(_translate("Form", "Помидор"))
        self.checkBox_8.setText(_translate("Form", "Огурец"))
        self.checkBox_13.setText(_translate("Form", "Морковь"))
        self.checkBox_14.setText(_translate("Form", "Лук"))
        self.Seafood.setText(_translate("Form", "Морепродукты"))
        self.checkBox_9.setText(_translate("Form", "Горбуша"))
        self.checkBox_10.setText(_translate("Form", "Мидии"))
        self.checkBox_11.setText(_translate("Form", "Тунец"))
        self.checkBox_12.setText(_translate("Form", "Креветки"))
        self.Pasta_title.setText(_translate("Form", "Макароны"))
        self.checkBox_15.setText(_translate("Form", "Вермишель"))
        self.checkBox_16.setText(_translate("Form", "Спагетти"))
        self.checkBox_17.setText(_translate("Form", "Рожки"))
        self.checkBox_18.setText(_translate("Form", "Фунчоза"))
        self.Mushrooms_title.setText(_translate("Form", "Грибы"))
        self.checkBox_21.setText(_translate("Form", "Шампиньоны"))
        self.checkBox_20.setText(_translate("Form", "Белые грибы"))
        self.checkBox_22.setText(_translate("Form", "Опята"))
        self.checkBox_19.setText(_translate("Form", "Лисички"))
        self.Fruits_title.setText(_translate("Form", "Фрукты"))
        self.checkBox_24.setText(_translate("Form", "Банан"))
        self.checkBox_23.setText(_translate("Form", "Яблоко"))
        self.checkBox_25.setText(_translate("Form", "Апельсин"))
        self.checkBox_26.setText(_translate("Form", "Дыня"))
        self.checkBox_27.setText(_translate("Form", "Киви"))
        self.Other_title.setText(_translate("Form", "Разное"))
        self.checkBox_31.setText(_translate("Form", "Яйцо"))
        self.checkBox_30.setText(_translate("Form", "Сыр"))
        self.checkBox_29.setText(_translate("Form", "Маргарин"))
        self.checkBox_28.setText(_translate("Form", "Укроп"))
        self.pushButton_3.setText(_translate("Form", "Посмотреть рецепт"))
        self.pushButton_4.setText(_translate("Form", "Посмотреть рецепт"))
        self.pushButton_2.setText(_translate("Form", "Посмотреть рецепт"))
        self.label_3.setText(_translate("Form", "Название продукта"))
        self.label_4.setText(_translate("Form", "Масса(гр.)"))
        self.pushButton_5.setText(_translate("Form", "Рассчитать"))
